version: '2.1'
services:
  line-bot-server:
    build: ./line-bot-server
    ports:
      - "${PORT_LINE_BOT_SERVER}:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      BASE_URL: ${BASE_URL}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      LINE_BROADCAST_GROUP_ID: ${LINE_BROADCAST_GROUP_ID}
    volumes:
      - ./utils:/app/utils
      - ./const:/app/const

  db:
    build: ./db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Taipei
      PGTZ: Asia/Taipei
    ports:
      - "${PORT_DB}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  scheduler:
    build: ./scheduler
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GOOGLE_SERVICE_ACCOUNT_CRED_FILE: ${GOOGLE_SERVICE_ACCOUNT_CRED_FILE}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
      GOOGLE_CALENDAR_SYNC_MIN_TIME: ${GOOGLE_CALENDAR_SYNC_MIN_TIME}
      NOTION_TOKEN: ${NOTION_TOKEN}
      NOTION_DATABASE_ID: ${NOTION_DATABASE_ID}
      NOTION_SYNC_MIN_TIME: ${NOTION_SYNC_MIN_TIME}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_BROADCAST_GROUP_ID: ${LINE_BROADCAST_GROUP_ID}
    volumes:
      - ./utils:/app/utils
      - ./const:/app/const
      - ./backup:/app/backup

volumes:
  db_data:
