services:
  line-bot-server:
    build: ./line-bot-server
    ports:
      - "${PORT_LINE_BOT_SERVER}:5000"
    environment:
      FLASK_ENV: development
      BASE_URL: ${BASE_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE:-}
      DB_SSLROOTCERT: ${DB_SSLROOTCERT:-}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      LINE_BROADCAST_GROUP_ID: ${LINE_BROADCAST_GROUP_ID}
      PROPERTY_NAME: ${PROPERTY_NAME}
      BANK_ACCOUNT_INFO: ${BANK_ACCOUNT_INFO}
    volumes:
      - ./utils:/app/utils
      - ./const:/app/const
      - ./certs:/app/certs:ro
      - /etc/localtime:/etc/localtime:ro

  scheduler:
    build: ./scheduler
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE:-}
      DB_SSLROOTCERT: ${DB_SSLROOTCERT:-}
      GOOGLE_SERVICE_ACCOUNT_CRED_FILE: ${GOOGLE_SERVICE_ACCOUNT_CRED_FILE}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
      GOOGLE_CALENDAR_SYNC_MIN_TIME: ${GOOGLE_CALENDAR_SYNC_MIN_TIME}
      NOTION_TOKEN: ${NOTION_TOKEN}
      NOTION_DATABASE_ID: ${NOTION_DATABASE_ID}
      NOTION_SYNC_MIN_TIME: ${NOTION_SYNC_MIN_TIME}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_BROADCAST_GROUP_ID: ${LINE_BROADCAST_GROUP_ID}
    volumes:
      - ./utils:/app/utils
      - ./const:/app/const
      - ./certs:/app/certs:ro
      - ./backup:/app/backup
      - /etc/localtime:/etc/localtime:ro
