import os

# LINE messaging API
LINE_CHANNEL_ACCESS_TOKEN = os.getenv('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = os.getenv('LINE_CHANNEL_SECRET')

# User commands
USER_COMMAND_SEARCH_BOOKING_BY_KEYWORD = '查詢訂單'

# Postback commands
POSTBACK_COMMAND_SEARCH_BOOKING_BY_CHECK_IN_DATE = 'POSTBACK.SEARCH_BOOKING_BY_CHECK_IN_DATE'
POSTBACK_COMMAND_VIEW_FULL_BOOKING_INFO = 'POSTBACK.VIEW_FULL_BOOKING_INFO'
POSTBACK_COMMAND_EDIT_BOOKING = 'POSTBACK.EDIT_BOOKING'
POSTBACK_COMMAND_CANCEL_BOOKING = 'POSTBACK.CANCEL_BOOKING'
