import os

# LINE messaging API
LINE_CHANNEL_ACCESS_TOKEN = os.getenv('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = os.getenv('LINE_CHANNEL_SECRET')

# COMMAND
COMMAND_BOOKING_LOOKUP = '查詢訂單'
COMMAND_SEARCH_BOOKING_BY_CHECK_IN_DATE = '以入住日查詢訂單'
