jobs:
  import_historical_bookings:
    enabled: "False"
    job_function: "import_historical_bookings"
    type: "startup"
  sync_bookings_to_google_calendar:
    enabled: "False"
    job_function: "sync_bookings_to_google_calendar"
    type: "cron"
    cron: "*/15 * * * *" # At every 15th minute.
  sync_bookings_with_notion:
    enabled: "False"
    job_function: "sync_bookings_with_notion"
    type: "cron"
    cron: "3,18,33,48 * * * *" # At minute 3, 18, 33, and 48.
  export_historical_bookings:
    enabled: "False"
    job_function: "export_historical_bookings"
    type: "cron"
    cron: "0 2 * * *" # Everyday at 02:00.
  backup_sql:
    enabled: "False"
    job_function: "backup_sql"
    type: "cron"
    cron: "0 3 * * *" # Everyday at 03:00.
  notify_daily_bookings:
    enabled: "False"
    job_function: "notify_daily_bookings"
    type: "cron"
    cron: "0 8 * * *" # Everyday at 08:00.
  notify_not_prepaid_bookings:
    enabled: "False"
    job_function: "notify_not_prepaid_bookings"
    type: "cron"
    cron: "0 13 * * 2" # At 13:00 on Tuesday.
