jobs:
  import_historical_bookings:
    enabled: "False"
    job_function: "import_historical_bookings"
    type: "startup"
  sync_bookings_to_google_calendar:
    enabled: "False"
    job_function: "sync_bookings_to_google_calendar"
    type: "cron"
    cron: "*/15 * * * *" # At every 15th minute.
  sync_bookings_with_notion:
    enabled: "False"
    job_function: "sync_bookings_with_notion"
    type: "cron"
    cron: "3,18,33,38 * * * *" # At minute 3, 18, 33, and 38.
