jobs:
  import_historical_bookings:
    enabled: "False"
    job_function: "import_historical_bookings"
    type: "startup"
  sync_bookings_to_google_calendar:
    enabled: "True"
    job_function: "sync_bookings_to_google_calendar"
    type: "cron"
    cron: "*/15 * * * *" # At every 15th minute.
