import os

# LINE messaging API
LINE_CHANNEL_ACCESS_TOKEN = os.getenv('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = os.getenv('LINE_CHANNEL_SECRET')

# User flows and steps
USER_FLOW_CREATE_BOOKING = 'USER_FLOW.CREATE_BOOKING'
USER_FLOW_STEP_CREATE_BOOKING__GET_CUSTOMER_NAME = 'USER_FLOW_STEP.CREATE_BOOKING.GET_CUSTOMER_NAME'
USER_FLOW_STEP_CREATE_BOOKING__GET_PHONE_NUMBER = 'USER_FLOW_STEP.CREATE_BOOKING.GET_PHONE_NUMBER'
USER_FLOW_STEP_CREATE_BOOKING__GET_CHECK_IN_DATE = 'USER_FLOW_STEP.CREATE_BOOKING.GET_CHECK_IN_DATE'
USER_FLOW_STEP_CREATE_BOOKING__GET_NUM_NIGHTS = 'USER_FLOW_STEP.CREATE_BOOKING.GET_NUM_NIGHTS'
USER_FLOW_STEP_CREATE_BOOKING__SELECT_ROOMS = 'USER_FLOW_STEP.CREATE_BOOKING.SELECT_ROOMS'
USER_FLOW_STEP_CREATE_BOOKING__GET_TOTAL_PRICE = 'USER_FLOW_STEP.CREATE_BOOKING.GET_TOTAL_PRICE'
USER_FLOW_STEP_CREATE_BOOKING__GET_PREPAYMENT = 'USER_FLOW_STEP.CREATE_BOOKING.GET_PREPAYMENT'
USER_FLOW_STEP_CREATE_BOOKING__SELECT_SOURCE = 'USER_FLOW_STEP.CREATE_BOOKING.SELECT_SOURCE'
USER_FLOW_STEP_CREATE_BOOKING__GET_NOTES = 'USER_FLOW_STEP.CREATE_BOOKING.GET_NOTES'
USER_FLOW_STEP_CREATE_BOOKING__CONFIRM = 'USER_FLOW_STEP.CREATE_BOOKING.CONFIRM'

USER_FLOW_EDIT_BOOKING = 'USER_FLOW.EDIT_BOOKING'
USER_FLOW_STEP_EDIT_BOOKING__SELECT_ATTRIBUTE = 'USER_FLOW_STEP.EDIT_BOOKING.SELECT_ATTRIBUTE'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_CUSTOMER_NAME = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_CUSTOMER_NAME'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_PHONE_NUMBER = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_PHONE_NUMBER'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_CHECK_IN_DATE = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_CHECK_IN_DATE'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_NUM_NIGHTS = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_NUM_NIGHTS'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_ROOMS = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_ROOMS'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_TOTAL_PRICE = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_TOTAL_PRICE'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_PREPAYMENT = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_PREPAYMENT'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_PREPAYMENT_STATUS = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_PREPAYMENT_STATUS'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_PREPAYMENT_NOTE = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_PREPAYMENT_NOTE'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_SOURCE = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_SOURCE'
USER_FLOW_STEP_EDIT_BOOKING__EDIT_NOTES = 'USER_FLOW_STEP.EDIT_BOOKING.EDIT_NOTES'
USER_FLOW_STEP_EDIT_BOOKING__CONFIRM = 'USER_FLOW_STEP.EDIT_BOOKING.CONFIRM'

USER_FLOW_CANCEL_BOOKING = 'USER_FLOW.CANCEL_BOOKING'
USER_FLOW_STEP_CANCEL_BOOKING__CONFIRM = 'USER_FLOW_STEP.CANCEL_BOOKING.CONFIRM'

USER_FLOW_RESTORE_BOOKING = 'USER_FLOW.RESTORE_BOOKING'
USER_FLOW_STEP_RESTORE_BOOKING__CONFIRM = 'USER_FLOW_STEP.RESTORE_BOOKING.CONFIRM'

USER_FLOW_PREPAID_BOOKING = 'USER_FLOW.PREPAID_BOOKING'
USER_FLOW_STEP_PREPAID_BOOKING__GET_PREPAYMENT_AMOUNT = 'USER_FLOW_STEP.PREPAID_BOOKING.GET_PREPAYMENT_AMOUNT'
USER_FLOW_STEP_PREPAID_BOOKING__GET_PREPAYMENT_NOTE = 'USER_FLOW_STEP.PREPAID_BOOKING.GET_PREPAYMENT_NOTE'
USER_FLOW_STEP_PREPAID_BOOKING__CONFIRM = 'USER_FLOW_STEP.PREPAID_BOOKING.CONFIRM'

USER_FLOW_CREATE_CLOSURE = 'USER_FLOW.CREATE_CLOSURE'
USER_FLOW_STEP_CREATE_CLOSURE__GET_START_DATE = 'USER_FLOW_STEP.CREATE_CLOSURE.GET_START_DATE'
USER_FLOW_STEP_CREATE_CLOSURE__GET_NUM_NIGHTS = 'USER_FLOW_STEP.CREATE_CLOSURE.GET_NUM_NIGHTS'
USER_FLOW_STEP_CREATE_CLOSURE__SELECT_ROOMS = 'USER_FLOW_STEP.CREATE_CLOSURE.SELECT_ROOMS'
USER_FLOW_STEP_CREATE_CLOSURE__GET_REASON = 'USER_FLOW_STEP.CREATE_CLOSURE.GET_REASON'
USER_FLOW_STEP_CREATE_CLOSURE__CONFIRM = 'USER_FLOW_STEP.CREATE_CLOSURE.CONFIRM'

# User commands
USER_COMMAND_SEARCH_BOOKING_BY_KEYWORD = '查詢訂單'
USER_COMMAND_SEARCH_BOOKING_BY_DATE = '查詢{date}的訂單'
USER_COMMAND_SEARCH_BOOKING_TODAY = '今日訂單'
USER_COMMAND_SEARCH_BOOKING_CHECK_OUT_TODAY = '今天退房'
USER_COMMAND_SEARCH_BOOKING_TOMORROW = '明日訂單'
USER_COMMAND_SEARCH_BOOKING_THIS_SATURDAY = '這週六訂單'
USER_COMMAND_SEARCH_BOOKING_LAST_SATURDAY = '上週六訂單'
USER_COMMAND_CONFIRM = '確認'
USER_COMMAND_CANCEL_CURRENT_FLOW = '取消'
USER_COMMAND_GO_TO_PREVIOUS_STEP_OF_CURRENT_FLOW = '上一步'
USER_COMMAND_CREATE_BOOKING = '建立訂單'
USER_COMMAND_EDIT_BOOKING = '更改訂單 {booking_id}'

# for both create and edit booking
USER_COMMAND_UPDATE_BOOKING__SELECT_CHECK_IN_DATE = '入住日期：{date}'
USER_COMMAND_UPDATE_BOOKING__SELECT_NUM_NIGHTS_1 = '1晚'
USER_COMMAND_UPDATE_BOOKING__SELECT_NUM_NIGHTS_2 = '2晚'
USER_COMMAND_UPDATE_BOOKING__SELECT_ROOMS_FINISH = '完成選擇'
USER_COMMAND_UPDATE_BOOKING__GET_NOTES_FINISH = '完成輸入'
USER_COMMAND_UPDATE_BOOKING__CONFIRM_FINISH = '確認新增訂單'

USER_COMMAND_EDIT_BOOKING__EDIT_CUSTOMER_NAME = '姓名'
USER_COMMAND_EDIT_BOOKING__EDIT_PHONE_NUMBER = '電話'
USER_COMMAND_EDIT_BOOKING__EDIT_DATES = '日期'
USER_COMMAND_EDIT_BOOKING__EDIT_ROOMS = '房間'
USER_COMMAND_EDIT_BOOKING__EDIT_TOTAL_PRICE = '總金額'
USER_COMMAND_EDIT_BOOKING__EDIT_PREPAYMENT = '訂金'
USER_COMMAND_EDIT_BOOKING__SET_PREPAYMENT_STATUS_UNPAID = '未付'
USER_COMMAND_EDIT_BOOKING__SET_PREPAYMENT_STATUS_PAID = '已付'
USER_COMMAND_EDIT_BOOKING__EDIT_PREPAYMENT_NOTE_FINISH = '完成輸入'
USER_COMMAND_EDIT_BOOKING__EDIT_SOURCE = '來源'
USER_COMMAND_EDIT_BOOKING__EDIT_NOTES = '備註'
USER_COMMAND_EDIT_BOOKING__FINISH = '結束更改'

# for cancel booking
USER_COMMAND_CANCEL_BOOKING__CONFIRM = '確認取消'
USER_COMMAND_CANCEL_BOOKING__CANCEL = '不要取消'

# for restore booking
USER_COMMAND_RESTORE_BOOKING__CONFIRM = '確認復原'
USER_COMMAND_RESTORE_BOOKING__CANCEL = '不要復原'

# for prepaid booking
USER_COMMAND_PREPAID_BOOKING__GET_PREPAYMENT_NOTE_FINISH = '完成輸入'
USER_COMMAND_PREPAID_BOOKING__CONFIRM_FINISH = '確認訂金資訊'

# for create closure
USER_COMMAND_CREATE_CLOSURE__SELECT_START_DATE = '入住日期：{date}'
USER_COMMAND_CREATE_CLOSURE__SELECT_NUM_NIGHTS_1 = '1晚'
USER_COMMAND_CREATE_CLOSURE__SELECT_NUM_NIGHTS_2 = '2晚'
USER_COMMAND_CREATE_CLOSURE__SELECT_ROOMS_FINISH = '完成選擇'
USER_COMMAND_CREATE_CLOSURE__GET_REASON_FINISH = '完成輸入'
USER_COMMAND_CREATE_CLOSURE__CONFIRM_FINISH = '確認關房'

# Postback commands
POSTBACK_COMMAND_LOOKUP_BOOKING = 'POSTBACK.LOOKUP_BOOKING'
POSTBACK_COMMAND_CREATE_BOOKING = 'POSTBACK.CREATE_BOOKING'
POSTBACK_COMMAND_CLOSE_ROOMS = 'POSTBACK.CLOSE_ROOMS'
POSTBACK_COMMAND_SHOW_MONTHLY_REPORT = 'POSTBACK.SHOW_MONTHLY_REPORT'
POSTBACK_COMMAND_SHOW_ROOM_PHOTOS = 'POSTBACK.SHOW_ROOM_PHOTOS'
POSTBACK_COMMAND_SEARCH_BOOKING_BY_DATE = 'POSTBACK.SEARCH_BOOKING_BY_DATE'
POSTBACK_COMMAND_VIEW_FULL_BOOKING_INFO = 'POSTBACK.VIEW_FULL_BOOKING_INFO'
POSTBACK_COMMAND_CANCEL_BOOKING = 'POSTBACK.CANCEL_BOOKING'
POSTBACK_COMMAND_RESTORE_BOOKING = 'POSTBACK.RESTORE_BOOKING'
POSTBACK_COMMAND_PREPAID_BOOKING = 'POSTBACK.PREPAID_BOOKING'
POSTBACK_COMMAND_CREATE_CLOSURE = 'POSTBACK.CREATE_CLOSURE'

POSTBACK_COMMAND_CREATE_BOOKING__SELECT_CHECK_IN_DATE = 'POSTBACK.CREATE_BOOKING.SELECT_CHECK_IN_DATE'
POSTBACK_COMMAND_EDIT_BOOKING__SELECT_CHECK_IN_DATE = 'POSTBACK.EDIT_BOOKING.SELECT_CHECK_IN_DATE'
POSTBACK_COMMAND_CREATE_CLOSURE__SELECT_START_DATE = 'POSTBACK.CREATE_CLOSURE.SELECT_START_DATE'
