import os

# LINE messaging API
LINE_CHANNEL_ACCESS_TOKEN = os.getenv('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = os.getenv('LINE_CHANNEL_SECRET')

# User flows and steps
USER_FLOW_CREATE_BOOKING = 'USER_FLOW.CREATE_BOOKING'
USER_FLOW_STEP_CREATE_BOOKING__GET_CUSTOMER_NAME = 'USER_FLOW_STEP.CREATE_BOOKING.GET_CUSTOMER_NAME'
USER_FLOW_STEP_CREATE_BOOKING__GET_PHONE_NUMBER = 'USER_FLOW_STEP.CREATE_BOOKING.GET_PHONE_NUMBER'
USER_FLOW_STEP_CREATE_BOOKING__GET_CHECK_IN_DATE = 'USER_FLOW_STEP.CREATE_BOOKING.GET_CHECK_IN_DATE'
USER_FLOW_STEP_CREATE_BOOKING__GET_NUM_NIGHTS = 'USER_FLOW_STEP.CREATE_BOOKING.GET_NUM_NIGHTS'
USER_FLOW_STEP_CREATE_BOOKING__SELECT_ROOMS = 'USER_FLOW_STEP.CREATE_BOOKING.SELECT_ROOMS'
USER_FLOW_STEP_CREATE_BOOKING__GET_TOTAL_PRICE = 'USER_FLOW_STEP.CREATE_BOOKING.GET_TOTAL_PRICE'
USER_FLOW_STEP_CREATE_BOOKING__GET_PREPAYMENT = 'USER_FLOW_STEP.CREATE_BOOKING.GET_PREPAYMENT'
USER_FLOW_STEP_CREATE_BOOKING__SELECT_SOURCE = 'USER_FLOW_STEP.CREATE_BOOKING.SELECT_SOURCE'
USER_FLOW_STEP_CREATE_BOOKING__GET_NOTES = 'USER_FLOW_STEP.CREATE_BOOKING.GET_NOTES'
USER_FLOW_STEP_CREATE_BOOKING__CONFIRM = 'USER_FLOW_STEP.CREATE_BOOKING.CONFIRM'

# User commands
USER_COMMAND_SEARCH_BOOKING_BY_KEYWORD = '查詢訂單'
USER_COMMAND_SEARCH_BOOKING_BY_CHECK_IN_DATE = '查詢{date}入住的訂單'
USER_COMMAND_SEARCH_BOOKING_CHECK_IN_TODAY = '今天入住'
USER_COMMAND_SEARCH_BOOKING_CHECK_OUT_TODAY = '今天退房'
USER_COMMAND_SEARCH_BOOKING_CHECK_IN_TOMORROW = '明天入住'
USER_COMMAND_SEARCH_BOOKING_CHECK_IN_THIS_SATURDAY = '這週六入住'
USER_COMMAND_SEARCH_BOOKING_CHECK_IN_LAST_SATURDAY = '上週六入住'
USER_COMMAND_CREATE_BOOKING = '建立訂單'
USER_COMMAND_CANCEL_CURRENT_FLOW = '取消'
USER_COMMAND_GO_TO_PREVIOUS_STEP_OF_CURRENT_FLOW = '上一步'

USER_COMMAND_CREATE_BOOKING__SELECT_CHECK_IN_DATE = '入住日期：{date}'
USER_COMMAND_CREATE_BOOKING__SELECT_NUM_NIGHTS_1 = '1晚'
USER_COMMAND_CREATE_BOOKING__SELECT_NUM_NIGHTS_2 = '2晚'
USER_COMMAND_CREATE_BOOKING__SELECT_ROOMS_FINISH = '完成選擇'
USER_COMMAND_CREATE_BOOKING__GET_NOTES_FINISH = '完成輸入'
USER_COMMAND_CREATE_BOOKING__CONFIRM_FINISH = '確認新增訂單'

# Postback commands
POSTBACK_COMMAND_SEARCH_BOOKING_BY_CHECK_IN_DATE = 'POSTBACK.SEARCH_BOOKING_BY_CHECK_IN_DATE'
POSTBACK_COMMAND_VIEW_FULL_BOOKING_INFO = 'POSTBACK.VIEW_FULL_BOOKING_INFO'
POSTBACK_COMMAND_EDIT_BOOKING = 'POSTBACK.EDIT_BOOKING'
POSTBACK_COMMAND_CANCEL_BOOKING = 'POSTBACK.CANCEL_BOOKING'

POSTBACK_COMMAND_CREATE_BOOKING__SELECT_CHECK_IN_DATE = 'POSTBACK.CREATE_BOOKING.SELECT_CHECK_IN_DATE'
